name: dbt_experiments
version: '1.0.0'
config-version: 2

profile: 'snowflake'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_experiments:
    src:
      +materialized: ephemeral
      +schema: src_views
    dim:
      +materialized: table
      +schema: dimension
    fact:
      +materialized: incremental
      +schema: fact
    mart:
      +schema: mart

    staging:
      +database: landing
      +schema: raw

seeds:
  +schema: seeds

snapshots:
  +schema: snapshots