name: dbt_experiments
version: '1.0.0'
config-version: 2

profile: 'snowflake'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:

  dbt_experiments:

    staging:
      +schema: staging
      +materialized: view
      covid:
    
    data_warehouse:
      +transient: false
      +schema: data_warehouse
      +materialized: incremental
      +query_tag: dw
      +tags:
        - "daily"

    data_mart:
      +transient: false
      +query_tag: dm
      +schema: data_mart
      +materialized: incremental
      +tags:
        - "daily"
        
  elementary:
    +database: covid
    +schema: elementary

seeds:
  +schema: seeds