name: dbt_experiments
version: '1.0.0'
config-version: 2

profile: 'snowflake'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:

  dbt_experiments:

    staging:
      +database: landing
      +schema: raw

    unloading:
      +database: landing
      +schema: raw

  elementary:
    +database: landing
    +schema: elementary

seeds:
  +schema: seeds