SHOW TABLES;

CREATE OR REPLACE SCHEMA ELEMENTARY;

CREATE STAGE AWS_COVID_STAGE
  URL='s3://ap-southeast-2-886192468297-covid/'
  STORAGE_INTEGRATION = AWS_COVID_STORAGE_INTEGRATION;

CREATE FILE FORMAT CSV_FORMAT
    type = 'csv' 
    compression = 'auto' 
    field_delimiter = ',' 
    record_delimiter = '\n'  
    field_optionally_enclosed_by = '\042' 
    PARSE_HEADER = true;

CREATE FILE FORMAT CSV_FORMAT_SKIP_HEADER
    type = 'csv' 
    compression = 'auto' 
    field_delimiter = ',' 
    record_delimiter = '\n'  
    field_optionally_enclosed_by = '\042' 
    skip_header = 1;

SELECT *
FROM TABLE(
INFER_SCHEMA(
  LOCATION=>'@AWS_COVID_STAGE/countries-aggregated.csv'
  , FILE_FORMAT=>'CSV_FORMAT'
  )
);

CREATE TABLE COUNTRIES_AGGREGATED
USING TEMPLATE (
SELECT array_agg(object_construct(*))
  FROM TABLE(
    INFER_SCHEMA(
      LOCATION=>'@AWS_COVID_STAGE/countries-aggregated.csv',
      FILE_FORMAT=>'CSV_FORMAT'
    )
  ));
DESC TABLE COUNTRIES_AGGREGATED;
COPY INTO COUNTRIES_AGGREGATED FROM @AWS_COVID_STAGE/countries-aggregated.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT_SKIP_HEADER');

CREATE TABLE KEY_COUNTRIES_PIVOTED
USING TEMPLATE (
SELECT array_agg(object_construct(*))
  FROM TABLE(
    INFER_SCHEMA(
      LOCATION=>'@AWS_COVID_STAGE/key-countries-pivoted.csv',
      FILE_FORMAT=>'CSV_FORMAT'
    )
  ));
DESC TABLE KEY_COUNTRIES_PIVOTED;
COPY INTO KEY_COUNTRIES_PIVOTED FROM @AWS_COVID_STAGE/key-countries-pivoted.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT_SKIP_HEADER');

CREATE TABLE REFERENCE
USING TEMPLATE (
SELECT array_agg(object_construct(*))
  FROM TABLE(
    INFER_SCHEMA(
      LOCATION=>'@AWS_COVID_STAGE/reference.csv',
      FILE_FORMAT=>'CSV_FORMAT'
    )
  ));
DESC TABLE REFERENCE;
COPY INTO REFERENCE FROM @AWS_COVID_STAGE/reference.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT_SKIP_HEADER');


CREATE TABLE TIME_SERIES_COVID_COMBINED
USING TEMPLATE (
SELECT array_agg(object_construct(*))
  FROM TABLE(
    INFER_SCHEMA(
      LOCATION=>'@AWS_COVID_STAGE/time-series-19-covid-combined.csv',
      FILE_FORMAT=>'CSV_FORMAT'
    )
  ));
DESC TABLE TIME_SERIES_COVID_COMBINED;
COPY INTO TIME_SERIES_COVID_COMBINED FROM @AWS_COVID_STAGE/time-series-19-covid-combined.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT_SKIP_HEADER');

CREATE TABLE US_CONFIRMED
USING TEMPLATE (
SELECT array_agg(object_construct(*))
  FROM TABLE(
    INFER_SCHEMA(
      LOCATION=>'@AWS_COVID_STAGE/us_confirmed.csv',
      FILE_FORMAT=>'CSV_FORMAT'
    )
  ));
DESC TABLE US_CONFIRMED;
COPY INTO US_CONFIRMED FROM @AWS_COVID_STAGE/us_confirmed.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT_SKIP_HEADER');

CREATE TABLE US_DEATHS
USING TEMPLATE (
SELECT array_agg(object_construct(*))
  FROM TABLE(
    INFER_SCHEMA(
      LOCATION=>'@AWS_COVID_STAGE/us_deaths.csv',
      FILE_FORMAT=>'CSV_FORMAT'
    )
  ));
DESC TABLE US_DEATHS;
COPY INTO US_DEATHS FROM @AWS_COVID_STAGE/us_deaths.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT_SKIP_HEADER');

CREATE TABLE US_SIMPLIFIED
USING TEMPLATE (
SELECT array_agg(object_construct(*))
  FROM TABLE(
    INFER_SCHEMA(
      LOCATION=>'@AWS_COVID_STAGE/us_simplified.csv',
      FILE_FORMAT=>'CSV_FORMAT'
    )
  ));
DESC TABLE US_SIMPLIFIED;
COPY INTO US_SIMPLIFIED FROM @AWS_COVID_STAGE/us_simplified.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT_SKIP_HEADER');

CREATE TABLE WORLDWIDE_AGGREGATE
USING TEMPLATE (
SELECT array_agg(object_construct(*))
  FROM TABLE(
    INFER_SCHEMA(
      LOCATION=>'@AWS_COVID_STAGE/worldwide-aggregate.csv',
      FILE_FORMAT=>'CSV_FORMAT'
    )
  ));
DESC TABLE WORLDWIDE_AGGREGATE;
COPY INTO WORLDWIDE_AGGREGATE FROM @AWS_COVID_STAGE/worldwide-aggregate.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT_SKIP_HEADER');