-- Integrations for COVID Data
CREATE STORAGE INTEGRATION AWS_COVID_STORAGE_INTEGRATION
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::886192468297:role/snowflake_role'
  STORAGE_ALLOWED_LOCATIONS = ('s3://ap-southeast-2-886192468297-covid/');
-- QB11547_SFCRole=2_qFSLeG1N0kKnn/Wn2KvjGcn+93E=

DESC INTEGRATION AWS_COVID_STORAGE_INTEGRATION;

GRANT USAGE ON INTEGRATION AWS_COVID_STORAGE_INTEGRATION TO ROLE TERRAFORM_ROLE;