WITH RAW_REVIEWS AS (
    SELECT * FROM {{ source('airbnb', 'reviews') }}
)
SELECT
    DATE AS REVIEW_DATE,
    COMMENTS AS REVIEW_TEXT,
    SENTIMENT AS REVIEW_STATEMENT,
    LISTING_ID AS LISTING_ID
FROM
 RAW_REVIEWS